### ISSUE TITLE
イベント後のゴミ処理

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-2#15]
>ゴミについて
>・持込まれた資材から出たゴミ お持ち帰りください。 
>・有料処分 行なっておりません。

会場からの注意事項的には↑とのこと。

@studiomohawk イベント後の懇親会ゴミが主になると思いますが、他のイベントのときどうされてました？

**Comment by studiomohawk** [comment]
執務フロアに持って行くと片付けておいてくれる。

**Comment by ahomu** [comment]
ガッテン！

**Comment by ahomu** [comment]
当日のスタッフオペレーションに組み込みます、とりま close
