### ISSUE TITLE
当日の撮影について

### ISSUE THREAD

**Issue by basara669** [insidefrontend/issue-2#33]
こんな構図は欲しいよとかそんなのを書く

**Comment by basara669** [comment]
## 注意ポイント！

https://github.com/insidefrontend/issue-2/tree/master/topics/seminars/saneyuki-microbench#%E3%83%A9%E3%82%A4%E3%83%96%E9%85%8D%E4%BF%A1%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89%E5%85%AC%E9%96%8B%E3%81%AA%E3%81%A9%E3%81%AE%E5%8F%AF%E5%90%A6

セミナーセッション `micro-benchmark is hard` は、ゲストスピーカーについては写真撮影しても公開不可、です。注意が必要。 via. https://github.com/insidefrontend/issue-2/pull/20#discussion_r161681260

**Comment by hiloki** [comment]
### ほしい構図

主にWebの素材として使うような想定です。
_※次回どうなるかわからないけど_

- AMAブースがいい感じにわちゃわちゃしそうなので、その雰囲気の画がほしい
- 縦向きでの構図も少しあると嬉しい。（Web/Mobile向け素材で使えるかも。

**Comment by basara669** [comment]
# 入場時
- [ ] 一人は1Fの入場の写真をとってほしい（ここは日が凄いあたっていい感じにとれる気がしてる
- [ ] あとは入場する人々的なものとかざわつき感のある感じの写真

# 開催後
- [ ]  協賛ブース的の写真
- [ ] AMA
- [ ] 登壇者（かっこよく
- [ ] 聞き入る参加者

# 片付け後
- [ ] 集合写真
- [ ] Tmixさん向けの素材

# 懇親会
- [ ] まぁ、いい感じに

**Comment by basara669** [comment]
2段階納品で考える

**Comment by basara669** [comment]
# 即納もの
- 来場者
- 晴れだったらビル的なもの
- 受付
- オープニングトーク
- 登壇の様子（登壇者1,2枚（CA社の方1と外部1））
- AMAの様子（AMA2つ分くらい（CA社の方1と外部1））
- 集合写真

**Comment by basara669** [comment]
倉長くんのを即納で、他の2人は一週間後

**Comment by basara669** [comment]
明日のMTGで倉長くんがいい感じに

**Comment by basara669** [comment]
終わったのでクローズ
