### ISSUE TITLE
会場の下見をする

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-2#4]
## [貸会議室　日経カンファレンスルーム](http://www.nikkei-hall.com/conference/index.html)

- 各部屋の広さ
- 廊下の広さ、セッション間移動時のキャパシティ
- 控え室ほかスタッフ動線の確認
- 無線 LAN の有無（来場者、スタッフ向け）
- 有線 LAN の有無（ライブ配信のため）
- etc

**Comment by studiomohawk** [comment]
有線LANはないと思う。。。

**Comment by studiomohawk** [comment]
無線LANはあるよ。

**Comment by ahomu** [comment]
無線 LAN は設備としてはないが、なにかデカい持ち運び機材があるとのこと。
ただしそれも一部屋までしかカバーできなそう。

**Comment by ahomu** [comment]
良い会場でした！
