### ISSUE TITLE
写真撮影の手配

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-2#7]
前回 https://github.com/insidefrontend/issue-1/issues/11

今回もヤフーさんの公式カメラ隊にご出動いただけるとありがたいですね...？

**Comment by ahomu** [comment]
https://github.com/insidefrontend/issue-2/tree/master/topics/seminars/saneyuki-microbench#%E3%83%A9%E3%82%A4%E3%83%96%E9%85%8D%E4%BF%A1%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89%E5%85%AC%E9%96%8B%E3%81%AA%E3%81%A9%E3%81%AE%E5%8F%AF%E5%90%A6

セミナーセッション `micro-benchmark is hard` は、ゲストスピーカーについては写真撮影しても公開不可、です。注意が必要。 via. https://github.com/insidefrontend/issue-2/pull/20#discussion_r161681260

**Comment by basara669** [comment]
@ahomu こちら弊社で担当します〜！

**Comment by basara669** [comment]
アサイン終わったので、撮影内容についてはこちらで議論
https://github.com/insidefrontend/issue-2/issues/33
