### ISSUE TITLE
グッズ、印刷物の用意

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-2#8]
前回 https://github.com/insidefrontend/issue-1/issues/12

- [x] ステッカー（ロゴ素材を直入稿で何とかなるハズ）
- [x] スタッフTシャツ|パーカー（あると中の人たちが嬉しい）
- [x] タイムテーブル（ちゃんと作るとかっこいい）
- [x] セッション/ブースごとの部屋の入り口にはる掲示物（ 14:00〜14:30 ほげほげセッション ）みたいな
- [ ] ~業者さん用の腕章 → 会場になにかあるだろうか...~
- [ ] ~参加証（ちゃんと作るとかっこいい）~

**Comment by hiloki** [comment]
# ステッカー

- 昨年の余剰があるのでそれを使うので、今回は発注なし。

# パーカー

- 本年も spicelife（TMIX）さんにグッズスポンサーになっていただき、5~6万円ほどでの発注をおねがいできそう。
- 色や生地については変更可能性あり。変更の場合はネイビーとする。

# タイムテーブル

- 昨年と同じフォーマットで作成したいが、多少のデザイン変更およびサイズ、枚数変更あり

# セッション/ブースごとの掲示物

- 去年の情報不明なので要確認
- AWAが大部屋でごった煮になるので、各エリアにわかりやすい掲示はほしい

# 腕章

- これはカメラクルー用であれば、Y!さんにおねがいするのがいいのかな... どうでしょう

**Comment by hiloki** [comment]
https://github.com/insidefrontend/issue2-goods
一通り対応した、はず。

- ポスターは Y! さん側でキンコーズ発注 @basara669 
- その他掲示物は日経さんのコピー機で刷ってもらう @studiomohawk

**Comment by hiloki** [comment]
無事一通り納品でFinishでした。
Special thanks: TMIX & @becyn
