### ISSUE TITLE
ケータリングの手配

### ISSUE THREAD

**Issue by ahomu** [insidefrontend/issue-2#9]
前年は https://github.com/insidefrontend/issue-1/issues/14 と https://github.com/insidefrontend/issue-1/issues/15

今回は近くにコンビニあったっけ...？ スタッフ向けの昼メシもあったほうがよいかも。

（前回 issue からの引用）

### AMAなど
- お菓子
- スタバのポット

### 出演者向け
- お弁当

### 登壇者、スタッフ向けの懇親会
- 美登利寿司（もしくはお寿司 😢 ）
- ピザ
- おかずっぽいやーつ（UBER EATSで良い感じのあれば、それで）
- お酒
- ソフトドリンク

### 食べ物以外で終日あったほうが良さそうなもの
- コップとかお皿
- ティッシュ
- ゴミ袋
- ウェットティッシュ

**Comment by basara669** [comment]
さて、やろう

**Comment by basara669** [comment]
メモ
- オードブルだけ西洋フードで、ピザや寿司頼むとかしたい
 - ピザ屋お寿司を運ぶ腕力は全然ある 💪 
- ゴミどうするか…(ピザ頼んでねーじゃねーか！的なやつ
- コーヒーは西洋フードにお任せする（お菓子系はどうするか
- 懇親会のドリンクも西洋フードにお任せする（備え付けの冷蔵庫とかに入れておいてくれそう

**Comment by studiomohawk** [comment]
ゴミはどの道自己回収なので、執務フロア側で処理しますよ。

**Comment by basara669** [comment]
@studiomohawk お、承知です〜！！

**Comment by basara669** [comment]
- コーヒーのポットのサービスなどは行なっていたりしますでしょうか？
  - 上記コーヒーを一気に飲めるわけではないので、分割に納品いただくことは可能でしょうか？
- オードブルなどを頼みたいのですが、何かメニューなどありますでしょうか？
- お酒などを頼んだ場合は、セットみたいなものを頼む感じになるのでしょうか？  
   それとも、「ビール2ケース」のような感じで個別で購入する感じになるのでしょうか？
- 支払い方法なのですが、クレジットカードでお支払いをしたいのですが、可能でしょうか？

**Comment by basara669** [comment]
http://www.catering-style.com/plan/?ca=5
http://tonky.jp/catering-plan/
http://sankeikaikan.co.jp/catering/partymenu/menu_03.html
https://goody-apt.jp/plan/
http://www.stylish-deli.jp/menu/?ca=47
https://pleasure-catering.com/plan_type/100%E5%90%8D%E4%BB%A5%E4%B8%8A%E3%81%AE%E3%83%91%E3%83%BC%E3%83%86%E3%82%A3/
http://www.platinumstyle-deli.jp/category/num/100-people/

**Comment by studiomohawk** [comment]
地下一階にセブン・イレブンがありますが、日・祝はお休みです。

- 至近な小さいナチュラル・ローソン(半蔵門線近く)は空いているはず……
- 向かいの大手町フィナンシャルシティというビルにはコンビニとかある、空いてるかは不明……

**Comment by basara669** [comment]
大手町で土日出勤したときの辛い思い出が…

**Comment by studiomohawk** [comment]
オフィスビルテナントはホワイト…

**Comment by basara669** [comment]
スタッフ食料はリサーチしておきます！！！

**Comment by basara669** [comment]
ケータリング done

**Comment by basara669** [comment]
# 最終的に発注したもの
## 登壇者向け
-  お弁当：21（発注済み）
-  飲み物：20（午前カクヤス）

## スタッフ向け
- おにぎりとかお菓子とか系:20000塩分（当日買いに行く）
- 飲み物：40本（午前カクヤス）

## 懇親会
- 西洋フーズ:108,216円（18時10分くらいに到着）
- カクヤス：19,494円（甘い飲み物系）（18時から19時に到着）

## 来場者向け
- お菓子大量

## その他（アマゾンで送付済み）
- ゴミ袋45リット50枚
- プラコップ
- ウェットティッシュ
- 普通のティッシュ
- マジック


## コーヒー
- 170杯
 - 午前中に120杯
 - 午後に50杯

**Comment by basara669** [comment]
西洋フーズさんの料理の量からの時間判断は勉強になった。
終わったのでクローズ
